# Generated by Django 4.0 on 2022-01-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='descripcion',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
